wireshark: update to 4.6.8

diff --git a/utilities/wireshark/tools/pre-commit b/utilities/wireshark/tools/pre-commit
--- a/utilities/wireshark/tools/pre-commit
+++ b/utilities/wireshark/tools/pre-commit
@@ -3,6 +3,9 @@
 #
 # For git user: copy tools/pre-commit to .git/hooks/ folder and make it
 # executable. To bypass it for a single commit, use the --no-verify argument.
+# Using --no-verify will then fail during git review because of a missing
+# ChangeID. Fix that by running git review -i. Do not use -i during normal
+# operation.
 #
 # Alternatively, invoke it directly with the commit ID. Example for checking the
 # last commit:
@@ -10,23 +13,26 @@
 #   tools/pre-commit HEAD~
 #
 # Relative paths are also supported. For instance, if you are in epan/, then you
-# could invoke `../tools/pre-commit HEAD` to check for changes to staged files.
+# could invoke  `../tools/pre-commit HEAD` to check for changes to staged files.
 #
 # From
 # http://mark-story.com/posts/view/using-git-commit-hooks-to-prevent-stupid-mistakes
 #
 
 # If the commit identifier is not given, use HEAD instead.
-COMMIT_ID="${1:-HEAD}"
+COMMIT_IDS=HEAD
+if [ $# -gt 0 ] ; then
+    COMMIT_IDS=$*
+fi
 
-UNAME=`uname -a`
+UNAME=$( uname -a )
 
 case "$UNAME" in
     *\ Msys)
         pyvar="pythonw.exe"
         ;;
     *)
-        pyvar="python"
+        pyvar="python3"
         ;;
 esac
 
@@ -37,63 +43,89 @@ hook_script=${GIT_DIR:-.git}/hooks/pre-commit
 
 # Always start in the root directory of the source tree, this allows for
 # invocations via relative paths (such as ../tools/pre-commit):
-cd "$(git rev-parse --show-toplevel)"
+if ! cd "$(git rev-parse --show-toplevel)" ; then
+    echo "Can't change to the top-level source directory."
+    exit 1
+fi
 
 # Check for newer (actually, different) versions of the pre-commit script
 # (but only if invoked as hook, i.e. the commit ID is not given as argument).
 if [ -z "$1" ] && [ -f "$hook_script" ]; then
     if ! cmp -s "$hook_script" tools/pre-commit; then
-        echo "Pre-commit hook script is outdated, please update!"
+        echo "Pre-commit hook script is outdated, please update! (cp tools/pre-commit ${hook_script})"
     fi
 fi
 
+have_diameter_files="False"
+bad_alloc_patterns=${PWD}/tools/detect_bad_alloc_patterns.py
 exit_status=0
 
-COMMIT_FILES=`git diff-index --cached --name-status ${COMMIT_ID} | grep -v "^D" | cut -f2 | grep "\.[ch]$"`
+for COMMIT_ID in $COMMIT_IDS; do
+    COMMIT_FILES=$( git diff-index --cached --name-status "${COMMIT_ID}" | grep -v "^D" | cut -f2 | grep "\\.[ch]$" )
+    if git diff-index --cached --name-status "${COMMIT_ID}" | grep -v "^D" | cut -f2 | grep diameter/ > /dev/null ; then
+        have_diameter_files="True"
+    fi
 
-# Path to filter script in the tools directory
-filter_script=${PWD}/tools/pre-commit-ignore.py
-filter_conf=${PWD}/tools/pre-commit-ignore.conf
+    # Path to filter script in the tools directory
+    filter_script=${PWD}/tools/pre-commit-ignore.py
+    filter_conf=${PWD}/tools/pre-commit-ignore.conf
 
-if [ ! -e "$filter_script" ]; then
-    echo "File '$filter_script' does not exist. Aborting."
-    exit 1
-fi
+    if [ -f "$filter_script" ] && [ -f "$filter_conf" ]; then
+        CHECK_FILES=$( echo "$COMMIT_FILES" | "$PYBIN" "$filter_script" "$filter_conf" ) || continue
+    else
+        CHECK_FILES="$COMMIT_FILES"
+    fi
 
-CHECK_FILES=`echo "$COMMIT_FILES" | "$PYBIN" "$filter_script" "$filter_conf"`
-if [ $? -ne 0 ]; then
-    exit 1
-fi
+    echo "$COMMIT_FILES" | $PYBIN "$bad_alloc_patterns"
 
-# On windows python will output \r\n line endings - we don't want that.
-#
-# Do not use sed, as not all versions of sed support \r as meaning CR
-# in a regexp - the only version that does so might be GNU sed; the
-# GNU sed documentation says that only \n and \\ can be used in a
-# portable script.
-#
-# The Single UNIX Specification says that tr supports \r; most if not
-# all modern UN*Xes should support it.
-CHECK_FILES=`echo "$CHECK_FILES" | tr -d '\r'`
+    # On windows python will output \r\n line endings - we don't want that.
+    #
+    # Do not use sed, as not all versions of sed support \r as meaning CR
+    # in a regexp - the only version that does so might be GNU sed; the
+    # GNU sed documentation says that only \n and \\ can be used in a
+    # portable script.
+    #
+    # The Single UNIX Specification says that tr supports \r; most if not
+    # all modern UN*Xes should support it.
+    CHECK_FILES=$( echo "$CHECK_FILES" | tr -d '\r' )
 
-for FILE in $CHECK_FILES; do
+    for FILE in $CHECK_FILES; do
+    # Skip some special cases
+    FILE_BASENAME="$( basename "$FILE" )"
+    # This should only be done on code that's part of one or more
+    # Wireshark programs; idl2wrs.c is a developer tool, not a
+    # Wireshark program, so these tests don't apply.
+    if test "$FILE_BASENAME" = "idl2wrs.c"
+    then
+        continue
+    fi
+    if test "$FILE_BASENAME" = "wmem_test.c"
+    then
+        continue
+    fi
 
     #Check if checkhf is good
-    ./tools/checkhf.pl $FILE            || exit_status=1
+    ./tools/checkhf.pl "$FILE"            || exit_status=1
 
     #Check if checkAPIs is good
-    ./tools/checkAPIs.pl -p $FILE       || exit_status=1
+    ./tools/checkAPIs.pl -p "$FILE"       || exit_status=1
 
     #Check if fix-encoding-args is good
-    ./tools/fix-encoding-args.pl $FILE  || exit_status=1
+    ./tools/fix-encoding-args.pl "$FILE"  || exit_status=1
 
     #Check if checkfiltername is good
-    ./tools/checkfiltername.pl $FILE    || exit_status=1
+    ./tools/checkfiltername.pl "$FILE"    || exit_status=1
 
+    # If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
+    git diff-index --check --cached "${COMMIT_ID}" "$FILE" || exit_status=1
+
+    done
 done
 
-# If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
-git diff-index --check --cached ${COMMIT_ID}    || exit_status=1
+if [ "$have_diameter_files" = "True" ]
+then
+    ./tools/validate-diameter-xml.sh > /dev/null || exit_status=1
+fi
 
 exit $exit_status
 
