gettext: update to 1.0

diff --git a/utilities/gettext/gettext-tools/tests/lang-pascal b/utilities/gettext/gettext-tools/tests/lang-pascal
--- a/utilities/gettext/gettext-tools/tests/lang-pascal
+++ b/utilities/gettext/gettext-tools/tests/lang-pascal
@@ -2,11 +2,11 @@
 . "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Object Pascal language.
-# Assumes the following packages are installed: fpk.
+# Assumes the following packages are installed: fpc.
 
-# Note: This test fails with fpk 1.0.10 when an UTF-8 locale is present,
-# because fpk ignores the locale's encoding. It supports only unibyte locales.
-# This here is a quick workaround:
+# Note: This test fails with fpk 1.0.10 ... 3.0.0 when an UTF-8 locale is
+# present, because fpk ignores the locale's encoding. It supports only unibyte
+# locales. This here is a quick workaround:
 UTF8_LOCALE_UNSUPPORTED=yes
 
 cat <<\EOF > pascalprog.pp
@@ -26,18 +26,25 @@ begin
 end.
 EOF
 
+(fpc pascalprog.pp) >/dev/null 2>&1 ||
 (ppc386 pascalprog.pp) >/dev/null 2>&1 ||
 (ppcx64 pascalprog.pp) >/dev/null 2>&1 ||
 {
-  echo "Skipping test: Pascal compiler ppc386 or ppcx64 not found"
+  echo "Skipping test: Pascal compiler fpc or ppc386 or ppcx64 not found"
   Exit 77
 }
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o pascalprog.tmp --omit-header --add-location pascalprog.rst || Exit 1
+# fpc 3.0.0 or newer produces a .rsj file instead of a .rst file.
+if test -f pascalprog.rsj; then
+  suffix=rsj
+else
+  suffix=rst
+fi
+${XGETTEXT} -o pascalprog.tmp --omit-header --add-location pascalprog.${suffix} || Exit 1
 LC_ALL=C tr -d '\r' < pascalprog.tmp > pascalprog.pot || Exit 1
 
-cat <<EOF > pascalprog.ok
+cat <<\EOF > pascalprog.ok
 #: pascalprog.question
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -77,7 +84,7 @@ test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/pascalprog.mo fr.po
+${MSGFMT} -c --no-convert -o fr/LC_MESSAGES/pascalprog.mo fr.po
 
 : ${DIFF=diff}
 cat <<\EOF > pascalprog.ok
@@ -92,14 +99,12 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR ./pascalprog > pascalprog.out || Exit 1
   : ${DIFF=diff}
   ${DIFF} pascalprog.ok pascalprog.out || Exit 1
 fi
 if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
   if test $LOCALE_FR_UTF8 != none; then
-    prepare_locale_ fr $LOCALE_FR_UTF8
     LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR_UTF8 ./pascalprog > pascalprog.out || Exit 1
     : ${DIFF=diff}
     ${DIFF} pascalprog.oku pascalprog.out || Exit 1
